const seedAnswers = [
    "St. James",
    "Peru",
    "Scotland",
    "Michael Jackson - Thriller",
    "Bern",
    "Swim",
    "Ukraine",
    "Istanbul",
    "World Wide Web",
    "Austria",
    "Northern Africa",
    "Canada",
    "Mexico",
    "Jamaica",
    "Egypt",
    "Germany",
    "Russia",
    "South Korea",
    "The Philippines",
    "Israel",
    "U.S textile and iron production tapered off",
    "The phonograph, the microphone, and the motion-picture camera",
    "Ten percent of American families owned 73 percent of the nation's wealth",
    "Separation from Britain was an illegal act that would ignite an unnecessary war",
    "Long Island",
    "Ill fed, ill clothed, and ill trained",
    "It was important to save England and France from defeat, but even more important for the U.S. to stay out of the war",
    "The government took over many industries and strictly limited the profits of others",
    "German-Americans",
    "Force Hitler to transfer troops and thereby lessen the pressure on the Soviet armies",
    "25.5",
    "1/55",
    "150",
    "502",
    "156",
    "81/3 gallons",
    "2400",
    "15",
    "1",
    "3 : 5",
    "Venus",
    "Charles Darwin",
    "Polaris",
    "Sunlight",
    "Bat",
    "Mutualism",
    "Newton",
    "Venus",
    "Pumice",
    "John Glenn",
    "Power Supply Unit",
    "No moving parts, less prone to damage",
    "CPU",
    "Redhat",
    "Disk Defragment",
    "Binary",
    "CPU",
    "SoC",
    "0",
    "193"
];

module.exports = seedAnswers;