const seedOptions = [
    "St. James",
    "St. John",
    "St. George",
    "St. Peter",
    "Peru",
    "Germany",
    "Sweden",
    "Spain",
    "Scotland",
    "England",
    "Wales",
    "Northern Ireland",
    "Michael Jackson - Thriller",
    "ACDC - Back in Black",
    "Elton John - Made in England",
    "Take That - The Circus",
    "Bern",
    "St. Gallen",
    "Zurich",
    "Geneva",
    "Swim",
    "Run 30 Mph",
    "Grow a 3rd ear in the Winter",
    "Stand on their two back legs with their front ones in the air for up to 48 minutes",
    "Ukraine",
    "Kazakhstan",
    "Norway",
    "Finland",
    "Istanbul",
    "Wellington",
    "Berlin",
    "Ankara",
    "World Wide Web",
    "World With Web",
    "World Wide Window",
    "Web Wide World",
    "Austria",
    "France",
    "Germany",
    "Italy",
    "Northern Africa",
    "Eastern Africa",
    "Southern Africa",
    "Central Africa",
    "Canada",
    "North America",
    "Hawaii",
    "Japan",
    "Mexico",
    "North America",
    "South America",
    "Argentina",
    "Jamaica",
    "Haiti",
    "Italy",
    "Greece",
    "Egypt",
    "Portugal",
    "Iran",
    "India",
    "Germany",
    "Russia",
    "Great Britain",
    "France",
    "Russia",
    "Germany",
    "Norway",
    "The United States",
    "South Korea",
    "Japan",
    "North Korea",
    "Indonesia",
    "The Philippines",
    "China",
    "Pakistan",
    "Lebanon",
    "Israel",
    "Jordan",
    "Syria",
    "United Arab Emirates",
    "U.S textile and iron production tapered off",
    "Boom-bust cycles produced two major depressions",
    "The number of persons in manufacturing quadrupled",
    "Immigration was on the rise",
    "The phonograph, the microphone, and the motion-picture camera",
    "The sewing machine",
    "Refrigerated rail cars",
    "A process for making steel",
    "Ten percent of American families owned 73 percent of the nation's wealth",
    "Fifty percent of American families--a large middle class--owned 73 percent of the nation's wealth",
    "Wealth was so evenly distributed that the U.S., unlike European countries, was in all respects a classless society",
    "Farmers and workers owned most of the means of production",
    "Separation from Britain was an illegal act that would ignite an unnecessary war",
    "Only independence could preserve the colonists' constitutional rights",
    "The king, not Parliament, was responsible for the problems facing the colonists",
    "Sam Adams was acting in the best interests of the colonists with his actions and words",
    "Long Island",
    "Trenton",
    "Saratoga",
    "Princeton",
    "Ill fed, ill clothed, and ill trained",
    "A well-trained army with a strong tradition of bravery under fire",
    "Buoyed by a string of exhilarating victories",
    "Floundering because of a lack of any effective or respected leaders",
    "It was important to save England and France from defeat, but even more important for the U.S. to stay out of the war",
    "The U.S. should have nothing whatsoever to do with European affairs",
    "England was just as much to blame for starting World War II as was Germany",
    "The U.S. should declare war on Germany because the defeat of England would pose a threat to American security",
    "The government took over many industries and strictly limited the profits of others",
    "The government imposed wage-and-price controls and rationing to combat inflation",
    "The government raised the income tax and introduced the payroll-deduction system to collect it more efficiently",
    "Farm income soared, unemployment disappeared, and real wages increased",
    "German-Americans",
    "Jewish-Americans",
    "Japanese-Americans",
    "African-Americans",
    "Force Hitler to transfer troops and thereby lessen the pressure on the Soviet armies",
    "Assist the British army in North Africa and protect British control of the Suez Canal",
    "Liberate Italy as soon as possible so that American troops would be free to turn to the war in the Pacific",
    "Force Japan to transfer troops and thereby lessen pressure on the American armies",
    "25.30",
    "25.5",
    "25.00",
    "12.25",
    "1/55",
    "55",
    "3/11",
    "1/11",
    "149",
    "166",
    "150",
    "151",
    "52",
    "502",
    "520",
    "5002",
    "78",
    "136",
    "156",
    "196",
    "15/2 gallons",
    "17/2 gallons",
    "19/2 gallons",
    "81/3 gallons",
    "2004",
    "2400",
    "1904",
    "1906",
    "15",
    "16",
    "18",
    "20",
    "1",
    "0",
    "8",
    "5",
    "6 : 10",
    "15 : 25",
    "0.75 : 1.25",
    "3 : 5",
    "Venus",
    "Pluto",
    "Jupiter",
    "Uranus",
    "Charles Darwin",
    "Issac Newton",
    "Johannes Kepler",
    "Albert Einstein",
    "Polaris",
    "Orion",
    "Rigal",
    "Alpha Centauri",
    "Sunlight",
    "Green Plants",
    "Producers",
    "Chlorophyll",
    "Bat",
    "Flea",
    "Crow",
    "Sparrow",
    "Mutualism",
    "Scavenger and its food",
    "Parasitism",
    "Commensalism",
    "Newton",
    "Kilogram",
    "Watt",
    "Mile",
    "Venus",
    "Mars",
    "Uranus",
    "Mercury",
    "Pumice",
    "Granite",
    "Obsidian",
    "Basalt",
    "John Glenn",
    "Jim Lovell",
    "Buzz Aldrin",
    "Neil Armstrong",
    "Power Supply Unit",
    "Power Stand Unit",
    "Power Station Unit",
    "Protective Supply Unit",
    "No moving parts, less prone to damage",
    "Cheaper per GB compared to a standard Hard Drive",
    "Slower transfer rates, so data is not corrupted",
    "Uses Magnetic Disks to retain data",
    "CPU",
    "PCI",
    "HDD",
    "PSU",
    "Redhat",
    "Vista",
    "Me",
    "XP",
    "Disk Defragment",
    "Word Processing",
    "Linux",
    "Internet Explorer",
    "Binary",
    "Hexadecimal",
    "Mneomics",
    "Octal",
    "CPU",
    "SSD",
    "ROM",
    "RAM",
    "SoC",
    "CPU",
    "GPU",
    "RAM",
    "0",
    "2",
    "1",
    "4",
    "193",
    "194",
    "195",
    "192"
]

module.exports = seedOptions;