const seedQuestions = [
    "Who is the Patron Saint of Spain ?",
    "Where are the Nazca lines ?",
    "In what Country was former Prime Minister Tony Blair born ?",
    "What is the best-selling Album of all time ?",
    "What is the Capital city of Switzerland ?",
    "Pigs cant fly, but which one of these CAN they do ?",
    "Which of these is known as little Russia ?",
    "Which of these is NOT a Capital City ?",
    "What does WWW stand for in a web address ?",
    "What country is the famous Spanish horse riding school ?",
    "Where is Algeria located ?",
    "Where is Ottawa located ?",
    "Where is Mexico City located ?",
    "Where is Kingston located ?",
    "Where is Cairo located ?",
    "Where is Berlin located ?",
    "Where is Moscow located ?",
    "Where is Seoul located ?",
    "Where is Manila located ?",
    "Where is Jerusalem located?",
    "Which of the following statements about the period 1860 to 1900 is not true ?",
    "Which of the following did Thomas Edison invent ?",
    "Approximately how was wealth distributed in America in 1890 ?",
    "American Tories (Loyalists) believed that ?",
    "During the first two years of the war, American were victorious at all of the following battles except the battle of ?",
    "The American army in the early years of the War for Independence can be characterized as ?",
    "In the fall of 1939, an overwhelming majority of the American people believed that ?",
    "Which of the following did not occur World War II ?",
    "Which of the following groups experienced the least amount of discrimination and prejudice in the U.S. during World War II ?",
    "One of the purposes of opening a 'second front' was to ?",
    "The average of first 50 natural numbers is ?",
    "A fraction which bears the same ratio to 1/27 as 3/11 bear to 5/9 is equal to ?",
    "The number of 3-digit numbers divisible by 6, is ?",
    "What is 1004 divided by 2 ?",
    "A clock strikes once at 1 o’clock, twice at 2 o’clock, thrice at 3 o’clock and so on. How many times will it strike in 24 hours ?",
    "125 gallons of a mixture contains 20% water. What amount of additional water should be added such that water content be raised to 25% ?",
    "106 × 106 – 94 × 94 = ?",
    "Which of the following numbers gives 240 when added to its own square ?",
    "Evaluation of 83 × 82 × 8-5 is ?",
    "The simplest form of 1.5 : 2.5 is ?",
    "The only planet that has a day longer than its year is ?",
    "The naturalist responsible for 'The Theory of Evolution by Natural Selection' is which one of the following ?",
    "The North Star is which one of the following ?",
    "All land-dwelling living things depend upon which of the following as the initial source of energy ?",
    "Which one of the following is a nocturnal animal ?",
    "A honey bee getting nectar or pollen from a flower is an example of which type of association ?",
    "The standard unit of measurement used for measuring force is which of the following ?",
    "Which of the following is the hottest planet ?",
    "What is the name of the igneous rock that is light enough to float ?",
    "Who was the first American to orbit the earth ?",
    "What does PSU stand for ?",
    "Which one of these is the benefit of an SSD ?",
    "What component consists of the ALU, CU and Registers ?",
    "Which one of the below is NOT a windows operating system ?",
    "Which one of these programs is an example of a utility software ?",
    "What is machine code written in ?",
    "Which component needs to be cooled when they are running ?",
    "In a typical smartphone, where would the processing happen ?",
    "In programming, How is the first element of an array defined ?",
    "What is the decimal value for the binary number 11000001 ?"
];

module.exports = seedQuestions;